---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2017-07-07 at 3-29-50 PM/Screen Shot 2017-07-07 at 3-29-50
      PM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/8850/articles/186303/master/file/figures/Screen%20Shot%202017-07-07%20at%203-29-50%20PM/Screen%20Shot%202017-07-07%20at%203-29-50%20PM.png"
    folder_url: "/users/8850/articles/186303/master/folder/figures/Screen Shot 2017-07-07
      at 3-29-50 PM"
